USE DCV_PI
GO

insert into dbo.DESENVOLVEDORES(Nome)
values
('Nenhum')
,('MARCO JUNIOR')
,('PABLO BARRETO')
,('GABRIEL DURAES')
,('CLAUDIO POPOLIN')
,('CHRISTIANO KACIO ALMEIDA')
,('RAFAEL PAES')
,('SILVIO MARTINS')
,('JOSE ALBERTO')
,('TELMO')
,('MICHAEL')