USE [DCV_PI]
GO

/****** Object:  Table [dbo].[DESENVOLVEDORES]    Script Date: 22/03/2024 16:28:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DESENVOLVEDORES](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](100) NOT NULL
) ON [PRIMARY]
GO
