--PORTAL DE INVESTIMENTO UTILITY

use DCV_INVESTIMENTO
go

ALTER PROCEDURE dbo.P_OBTER_GESTORES_DRIVE
AS
BEGIN
	select * from GestorFundosDRIVEAMNET
	ORDER BY IdGestor
END

CREATE PROCEDURE dbo.P_OBTER_FUDNOS_GESTORES_DRIVE
AS
BEGIN
	select * from FundosDRIVEAMNET
	ORDER BY IdGestor
END

GRANT EXEC ON OBJECT::dbo.P_OBTER_GESTORES_DRIVE TO  USER_INVESTIMENTO
GRANT EXEC ON OBJECT::dbo.P_OBTER_FUDNOS_GESTORES_DRIVE TO  USER_INVESTIMENTO

--PERMISSÕES NECESSÁRIAS NA INFOBANC

USE AB_INFOBANC
GO

GRANT EXEC ON OBJECT::dbo.P_OBTER_GERENTE TO USER_PI
GRANT EXEC ON OBJECT::dbo.P_OBTER_LISTA_GERENTES TO USER_PI

USE INFOTREASURY
GO

GRANT SELECT ON dbo.Parametros_basicos TO USER_PI;

use DCV_PI
GO

GRANT EXEC ON OBJECT::dbo.P_OBTER_DATA_GIRO TO  USER_PI