USE AB_INFOBANC
GO


CREATE PROCEDURE dbo.P_OBTER_GERENTE  
@CODEXTERNO VARCHAR(8)  
AS  
BEGIN  
SELECT CODGERENTE AS 'CODEXTERNO', NOME,TIPOGERENTE,EMAIL,CODCCUSTO FROM GERENTES  
WHERE CODGERENTE = @CODEXTERNO  
END