use DCV_PI
go

IF @@SERVERNAME = 'SDAYSP03001'
	BEGIN
		GRANT EXEC ON TYPE::dbo.BranchTableType  TO  USER_PI
	END
ELSE
	BEGIN
		GRANT EXEC ON TYPE::dbo.BranchTableType  TO  USER_PI
	END

PRINT 'PERMISSÕES EXECUTAS EM: ' + @@SERVERNAME